### ISSUE TITLE
recode is not available in Debian-Based Distro

### ISSUE THREAD

**Issue by alxb421** [axtloss/vAssistant#1]
**user@host:~$**  pip3 install recode
```
ERROR: Could not find a version that satisfies the requirement recode (from versions: none)
ERROR: No matching distribution found for recode
```

**Comment by Nadeem-05** [comment]
yes

**Comment by axtloss** [comment]
What distro are you using? The error only wont really help

**Comment by alxb421** [comment]
> What distro are you using? The error only wont really help

pearOS ThiccSur (debian based Linux Distro)

Possible fix: compile the recode from source. Close this thread

**Comment by axtloss** [comment]
I checked, you can just do sudo apt install recode, it works on pearos
